package cn.xlink.cmmqttclient.queue;

public enum QueueType {

  MQTT_CONNACK,
  ASYNC_MQTT_SEND,
  LOGIC_MQTT_RECEIVE,
  LOGIC_PTP_CHANNEL_MESSAGE, 
  LOGIC_MQTT_SEND, 
  ASYNC_PTP_DEVICE_ONLINE,
  ASYNC_PTP_DEVICE_OFFLINE,
  ASYNC_MQTT_CONNACK,
  ;


}
